name: industrial_monitor
description: A modern Flutter app for monitoring industrial unit parameters
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^8.0.2
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: 21.2.4
  flutter_svg: ^2.0.7
  intl: 0.17.0
  flutter_animate:
  lucide_icons:

  # State Management
  provider: ^6.0.5
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  
  # Utils
  uuid: ^4.5.1
  logger: ^2.5.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/